#!/usr/bin/env zsh

# xcodebuild path
# Xcode.app/Contents/Developer/usr/bin/xcodebuild

source ~/.secrets

export IOS_BUILD_DIR="platforms/ios/build"
export ANDROID_SDK_VERSION="4.35.0"
export ANDROID_HOME="/usr/local/opt/android-sdk"
export ANDROIDSDK="/usr/local/opt/android-sdk"
export ANDROIDNDK="/usr/local/opt/android-ndk"
export ANDROIDAPI="15"  # Minimum API version your application require
export ANDROIDNDKVER="r14"  # Version of the NDK you installed
export freshebtserver="$HOME/propel/freshebt-server"
export freshebtapp="$HOME/propel/freshebt-app"

alias cdserver="cd $freshebtserver"
alias cdapp="cd $freshebtapp"
alias ds="$freshebtserver/docker-shell"
alias efs='ds psql efs'
alias migrate='ds manage migrate'
alias ptest'ds pytest'
alias ttests='ds trial'
alias fcov='open htmlcov/index.html'
alias tcov='open ebtbalance/htmlcov/index.html'
alias listroutes='ds manage list_routes'
alias tf='terraform'
alias venvserver='source ~/.virtualenvs/freshebt-server/bin/activate'
alias venvboto3moto='source ~/.virtualenvs/boto3moto/bin/activate'
alias venvtest='source ~/.virtualenvs/test/bin/activate'
alias f8='flake8'
alias listdevices='adb devices'
alias phonelogs='adb logcat'
alias ingrok='ngrok http 1337'
alias fixtranslations='ds manage update_i18n'
alias stageproxy='ansible-playbook -i devops/inventory/staging devops/proxy.yml'

alias simid="xcrun simctl list | grep Booted | grep -oE '(\w+-\w+)+'"
alias installapp="xcrun simctl install $(simid) $IOS_BUILD_DIR/emulator/Fresh\ EBT.app"

alias uninstallandroid='adb uninstall com.propel.ebenefits > /dev/null'
alias installandroid="adb install $freshebtapp/platforms/android/build/outputs/apk/android-debug.apk"

# show which ports are listening for TCP connections on redhat machines
# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Security_Guide/s1-server-ports.html
alias listen='nmap -sT -O localhost'

function stageefs() {
    pushd $freshebtserver 1> /dev/null
    ./deploy.sh staging $1
    popd
}

function pssh() {
    ssh -i ~/.ssh/keys/efs-production.pem ec2-user@$1
}

function resetplatforms() {
    gulp clean
    cordova platform rm android
    cordova platform rm ios
    rm -rf plugins
    gulp clean
    cordova platform add android@6.3.0 --nosave
    cordova platform add ios --nosave
}

function appetizeios() {
    gulp build-ios
    rm -rf "${IOS_BUILD_DIR}/FreshEBT.zip"
    zip -r "FreshEBT.zip" ${IOS_BUILD_DIR}/emulator/*
    appetize=`curl https://$APPETIZE_KEY@api.appetize.io/v1/apps -F "file=@FreshEBT.zip" -F "note=branch:ilya-test-1, build: #1" -F "platform=ios"`
    ios_url=`echo $appetize | jq .publicURL`
    echo $ios_url
}
