#!/usr/bin/env zsh

# xcodebuild path
# /Users/ilyakamens/Desktop/Xcode.app/Contents/Developer/usr/bin/xcodebuild

source ~/.secrets

export IOS_BUILD_DIR="platforms/ios/build"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home"
export ANDROID_HOME="/usr/local/android"
export ANDROID_SDK_ROOT="/usr/local/android"
export ANDROIDSDK="/usr/local/android"
export GRADLE_HOME="/opt/gradle/gradle-5.3.1"
export PATH=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Support:$PATH
export PATH=$ANDROID_SDK_ROOT/tools/bin:$PATH
export PATH=~/Desktop/apache-maven-3.6.0/bin:$PATH
export PATH="/usr/local/android/platform-tools:$PATH"
export PATH=$GRADLE_HOME/bin:$PATH
export PATH="/opt/gradle/gradle-4.10.2/bin:$PATH"

export propel="$HOME/dev/propel"
export freshebtserver="$propel/freshebt-server"
export freshebtvue="$propel/freshebt-vue"
export freshcardapp="$propel/orchard/apps/freshcard-app"
export orchard="$propel/orchard"
export freshcardserver="$propel/freshcard-server"
export propelinfra="$propel/propel-infrastructure"

export KG="$propelinfra/terraform/global/kubeconfig_propel-eks-global"
export KD="$propelinfra/terraform/development/kubeconfig_propel-eks-development"
export KS="$propelinfra/terraform/staging/kubeconfig_propel-eks-staging"
export KP="$propelinfra/terraform/production/kubeconfig_propel-eks-prod"

alias cdp="cd $propel"
alias cdserver="cd $freshebtserver"
alias cdv="cd $freshebtvue"
alias listdevices='adb devices'
alias phonelogs='adb logcat'
alias ingrok='ngrok http 1337'
alias fixtranslations='ds manage update_i18n'

# alias simid="xcrun simctl list | grep Booted | grep -oE '(\w+-\w+)+'"
# alias installapp="xcrun simctl install $(simid) $IOS_BUILD_DIR/emulator/Fresh\ EBT.app"

alias uninstallandroid='adb uninstall com.propel.ebenefits > /dev/null'
alias installandroid2="adb install ~/android-debug.apk"

# Kubectl aliases
alias kg="KUBECONFIG=$propelinfra/terraform/global/kubeconfig_propel-eks-global kubectl"
alias kd="KUBECONFIG=$propelinfra/terraform/development/kubeconfig_propel-eks-development kubectl"
alias ks="KUBECONFIG=$propelinfra/terraform/staging/kubeconfig_propel-eks-staging kubectl"
alias kp="KUBECONFIG=$propelinfra/terraform/production/kubeconfig_propel-eks-prod kubectl"

# Istioctl aliases
alias istg="istioctl --kubeconfig $propelinfra/terraform/global/kubeconfig_propel-eks-global"
alias istd="istioctl --kubeconfig $propelinfra/terraform/development/kubeconfig_propel-eks-development"
alias ists="istioctl --kubeconfig $propelinfra/terraform/staging/kubeconfig_propel-eks-staging"
alias istp="istioctl --kubeconfig $propelinfra/terraform/production/kubeconfig_propel-eks-prod"

# Helm aliases
alias hg="KUBECONFIG=$propelinfra/terraform/global/kubeconfig_propel-eks-global helm"
alias hd="KUBECONFIG=$propelinfra/terraform/development/kubeconfig_propel-eks-development helm"
alias hs="KUBECONFIG=$propelinfra/terraform/staging/kubeconfig_propel-eks-staging helm"
alias hp="KUBECONFIG=$propelinfra/terraform/prod/kubeconfig_propel-eks-prod helm"

# K8s helpers
dpods() {
    if [[ $# -lt 2 ]]; then
        echo "Example usage: dpods d papi"
        return
    fi

    pods="k$1 -n shared get pods --no-headers -o custom-columns=\":metadata.name\" | grep $2"
    for pod in $(eval $pods);
    do
        eval "k$1 -n shared delete pod $pod"
    done
}

source ~/.android-config

FRESHCARD_SERVER_SETUP_ENV="$freshcardserver/bin/setup-env"
if [[ -r "${FRESHCARD_SERVER_SETUP_ENV}" ]]; then
    . "${FRESHCARD_SERVER_SETUP_ENV}"
fi

FRESHCARD_APP_SETUP_ENV="${freshcardapp}/bin/setup-env"
if [[ -r "${FRESHCARD_APP_SETUP_ENV}" ]]; then
    . "${FRESHCARD_APP_SETUP_ENV}"
fi

ORCHARD_SETUP_ENV="${orchard}/bin/setup-env"
if [[ -r "${ORCHARD_SETUP_ENV}" ]]; then
    . "${ORCHARD_SETUP_ENV}"
fi
